dist: precise
language: java
branches:
  only:
  - master
  - develop
before_install:
- chmod +x gradlew
install: true
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/nablarch-build.sh
- $HOME/build-script/travis-ci/upload-test-report.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: GHibJSzPYcEyYOjbzxJZJFPK/aQqTcWPPj60Rf13kZhqcwWSChd9x8eU6H9775QPrOMhiGj/l6VxnWmo/EM4jPE14ZzsRSisbCfLl5AqUAg9L9saN0lPEZWdvr49SCs0X6MOjh9uqk0g5nurY79sSXGu34h5vuRur8uf0MHK1HsjuX6klgNKTU21VS+o/3k7EjKWxPDB7GWYodAWkme/hNl+tMjHtFELOka8XwBXj/kuT0Yo/GfU67RH0P5OrqMamhrzgOlfvaTkNKI7ZykgoK2ctDshKD2JBacBCv3ANOzIgJByhzFbS/lFQbkyhkwz1cw4ph/iJzN1cNSqhJRc4PORw8DArfE3YOeHhpo39MQ0IeS54StcLaI60xXkCGiWta2Qom/bVAz6I8EL6MqNSzIixrWh2ZY4cCNcqmWppwI7kK9jV+j44t8Sc765dX+9oyysgBaIK9iQwhpwYnMwOaC5+fXCUH/oY5/+xXSPs/MkfIa27owno6RgkCYb/wdHf2QQuKCipxd6Se5145Ki4U9rMYAB45cEVOpx5brMs3qDiQNL7vHd1jTnfokBxguvEbjEHZmqmtcGvX546Q99FnN4TKENu68Hrbwb68x41y0Tp3ZkxjOIxzVw6eiiQ4M0wdJpmYzC5u071PEvi9c+4zPR0K1OHvpQYWQ56JHVEcM=
