SELECT_SINGLE_RECORD =
SELECT COL1,
       COL3
  FROM TEST_TABLE
 WHERE COL1 = '10001'

SELECT_MULTI_RECORDS =
 SELECT COL1,
        COL2,
        COL3
   FROM TEST_TABLE
  WHERE COL3 > 20000
  ORDER BY COL1 DESC

 SELECT_NOTHING =
 SELECT COL1,
        COL2,
        COL3
   FROM TEST_TABLE
  WHERE COL3 < 100
  ORDER BY COL1 DESC

SELECT_FAILED =
SELECT COL1,
       COL_NOT_EXIST
  FROM TEST_TABLE
 WHERE COL1 = '10001'
