DROP TABLE PERSON;
CREATE TABLE PERSON (
  LINE_NUMBER number(18) NOT NULL,
  PERSON_ID number(9) NOT NULL,
  AGE number(3) NOT NULL,
  NAME nvarchar2(256) NOT NULL,
  PRIMARY KEY (LINE_NUMBER)
);
exit;